name: Update Fan Counts
on:
  schedule:
    - cron: '0 22 * * *'  # Daily at 5:00 GMT+7 (22:00 UTC)
    - cron: '0 10 * * *'  # Daily at 17:00 GMT+7 (10:00 UTC)
  workflow_dispatch:     # Manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4
        
    - name: Update fan counts
      run: python count.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'Kabigon (github-actions)'
        git config --global user.email 'kabigon.snorlax@gmail.com'
        git add data.json

        # Check if there are changes to commit
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update fan counts : $(date +'%Y-%m-%d')"
          git push
          echo "Changes committed and pushed"
        fi